Repository haskell-nix/hnix, pull requests merged in 2020-05, with the labels that each got.

#559 dep: upd dependent-sum (0.6->0.7)
  hnix.cabal
Labels: dependency update

#572 README: add Latest release on Hackage badge
  README.md
Labels: automation

#573 README: add dependencies status badge monitor
  README.md
Labels: automation

#579 default.nix: clean-up old overrides
  default.nix
Labels: dependency update, refactoring

#582 Repl.hs: import: Repline: hide options
  main/Repl.hs
Labels: minor

#580 default.nix: dep: upd hnix-store 0.2
  default.nix
Labels: dependency update, refactoring

#574 README: fix for the Hackage Matrix Builder badge
  README.md
Labels: minor

#540 Use haskeline-0.8
  hnix.cabal
  main/Repl.hs
  src/Nix/Fresh.hs
  src/Nix/Standard.hs
  src/Nix/Utils/Fix1.hs
Labels: challenging, dependency update, refactoring
